### ISSUE TITLE
No md5sum on OSX

### ISSUE THREAD

**Issue by chadbrewbaker** [DavyLandman/csvtools#11]
Had to replace md5sum with "openssl md5" on OSX. Is openssl common enough on Linux, or should I make a pull request that has the Makefile determine if it is building for OSX?

Also, I have a Haskell Criterion benchmark wrapper. Want me to host on my github or want me to do a pull request with a bench_crit Make option? Just Stack config files and a small Haskell script.

Looking into adding streaming top-k, t-digest, ... spiking with a script around Algebird to get a baseline.

**Comment by DavyLandman** [comment]
Hmm, a victim of my overly broad homebrew installs.

Okay, I think you could also change the script that uses it. Creating a variable in the top that either points to `md5sum` or `openssl md5` or another checksum tool, and use that variable?

Regarding your other questions: if you can explain what (preferable in a separate issue/pull request) the Haskall Criterion wrapper offers this repo (pros/cons)? And if the the haskall dependency is only for the benchmarks, yes this could be a useful addition.

the additions of new tools: sounds cool, looking forward to your pull requests! 

Could you explain what you mean with:
>  spiking with a script around Algebird to get a baseline.
?

**Comment by chadbrewbaker** [comment]
Submitted a PR on just the md5sum issue. Need some more work on the Criterion benchmarks. Open this in a browser for an example Criterion report, https://raw.githubusercontent.com/chadbrewbaker/rosalind/master/DNA/count.html

**Comment by DavyLandman** [comment]
okay, so #12 is merged.

criterion looks pretty, if you can keep the dependency separated, I'm all fine with merging it.
